name: E2E on Chrome

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.bun
          key: ${{ runner.os }}-node-${{ hashFiles('**/bun.lockb') }}

      - name: install dependencies and verify Cypress
        run: |
          bun ci
          bun cypress verify
          bun cypress info
          bun cypress version
          bun cypress version --component package
          bun cypress version --component binary
          bun cypress version --component electron
          bun cypress version --component node

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          project: ./site
          browser: chrome
          build: bun build
          start: bun start
          wait-on: "http://localhost:3000"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
